### PR TITLE
Quest Fixes + MySQL 8 Compatibility in Core

### PR DESCRIPTION
**Pull request by SoulSeekkor**
This fixes a massive number of quest chances (that I've gotten to so far).  There are a number of broken quests and other things I've fixed as well.  This includes escaped reserved works in the core which allows the core to run using MySQL 8 without issues.

I've found an issue with creatures that have a drop table but with items that are almost never going to drop (less than 1% chance for all of them) and a quest item will cause the quest item to basically never drop.  A prime example is the "Thresher Oil" item I've fixed, by fixing the drop table for that creature it now drops properly (because other things are dropping with it).  I believe this affects previous things like the heart of mokk as well, since those creatures probably have no drop table at all (except for the quest item).

### CODE REVIEW

**Comment by dufernst** [comment]
@SoulSeekkor I hadn't noticed you opened a merge request for this.
Thanks for doing so, I will take a look next week (although probably next Friday or Saturday).

**Comment by SoulSeekkor** [comment]
Sounds good!  Thanks! :)

**Comment by eXPeRi91** [comment]
Now this is good work.

**Comment by dufernst** [comment]
@SoulSeekkor manually reworked your SQL changes and committed them with you as author here:
https://github.com/dufernst/LegionCore-7.3.5/commit/7beb47582a614f1093691510d9655e152de911d0

To properly review them I had to look at what had exactly changed. In doing so converted everything to `UPDATE` statements so it becomes easier to see.

I can just cherry pick the one commit for the MySQL support code changes, or if you feel like it, I also wouldn't mind just having a separate pull request for it to just be able to click.
I'll either way look at it Monday, but looks good from a quick glance 👍 

Thank you for contributing the changes back, much appreciated.

**Comment by SoulSeekkor** [comment]
Thank you @dufernst!  I'm good with that, as long as the needed deletes are in there as I know I removed a few drop chance records that should not have been in the database at all. :)  I'll assume you have that all taken care of!

I should be able to open a new pull request for just the MySQL stuff, I'll try to do that here shortly!  The next big step (and why I named the files like I did, thanks for cleaning that up for now by the way!), is to incorporate the database updater like AzerothCore and current TrinityCore has, that's the ultimate goal at least!

**Comment by SoulSeekkor** [comment]
As a side note I thought about how it was harder to see what changed, I do like that with the UPDATE statements.  I believe AzerothCore does DELETE/INSERT pairs so I was going off that, but I do like the specific changes history that gives.  I'll work on doing it that way going forward as well!

**Comment by dufernst** [comment]
> Thank you @dufernst! I'm good with that, as long as the needed deletes are in there as I know I removed a few drop chance records that should not have been in the database at all. :) I'll assume you have that all taken care of!
> 
> I should be able to open a new pull request for just the MySQL stuff, I'll try to do that here shortly! The next big step (and why I named the files like I did, thanks for cleaning that up for now by the way!), is to incorporate the database updater like AzerothCore and current TrinityCore has, that's the ultimate goal at least!

I'll look at the new merge request, and will close this one as everything else has already been merged 👍

**Pull request closed without merging**
