### PR TITLE
Cmake update build system

### PR DESCRIPTION
**Pull request by ReyDonovan**
cotire
target interface
fix warning police
support cmake 3.16.0
update openssl macro
14 standart

test build 
VS 2022
boost 1.65.1
mysql 5.7
openSSL 1.1.1

### CODE REVIEW

**Comment by ReyDonovan** [comment]
test and work

**Comment by Lerduzz** [comment]
I am testing this...

**Comment by Lerduzz** [comment]
TESTED AND WORKS GREAT!
This fix an issue that I report today.
Closes: #194

**Comment by dufernst** [comment]
Well with 1 more person saying it works well, I am comfortable enough with merging this.
Thanks for the merge request :1st_place_medal:

**Pull request merged**
